[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "async-lab-specialized-agent"
version = "0.1.0"
requires-python = ">=3.11,<3.15"

dependencies = [
    "deepagents==0.7.0",
    "langgraph>=1.0.0,<2.0",
    "langchain-openai",
    "langgraph-cli[inmem]>=0.4.0",
    "pandas>=2.2.0",
    "langchain-deepseek>=1.1.0",
]
