import os
from pathlib import Path

import markdown as md
import nh3
from deepagents import FilesystemPermission, create_deep_agent
from deepagents.backends import FilesystemBackend
from langchain_core.tools import tool
from tavily import TavilyClient

from models import model

DATA_DIR = Path(__file__).resolve().parent / "homework_data"
DATA_DIR.mkdir(exist_ok=True)

_tavily = TavilyClient(api_key=os.environ.get("TVILY_API_KEY"))


@tool("search_news", description="网络搜索工具")
def search_news(query: str):
    return _tavily.search(query=query, max_results=8)


_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ max-width: 760px; margin: 40px auto; padding: 0 20px;
          font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
          line-height: 1.6; color: #1a1a1a; }}
  h1 {{ font-size: 2rem; border-bottom: 3px solid #006DDD; padding-bottom: .3em; }}
  h2 {{ color: #006DDD; margin-top: 1.6em; }}
  footer {{ margin-top: 3em; color: #777; font-size: .85rem;
            border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body>
{body}
<footer>Generated by a Deep Agents subagent team.</footer>
</body>
</html>"""


@tool(description="将markdown转换为html")
def markdown_to_html(markdown_text: str, title: str) -> str:
    body = md.markdown(markdown_text, extensions=["tables", "fenced_code"])
    body = nh3.clean(body)
    return _HTML_TEMPLATE.format(title=title, body=body)


GENRE_SYSTEM_PROMPT = """
你是一个旅游攻略研究智能体，正在调研一个地区的旅游。

你将被分配一个地区，以及一个研究文件夹。

工作方式：
1. 使用 search_news 查找最近这个地区相关的新闻、旅游攻略、值得游玩的景点。多搜索几次
2. 把你所有搜索的【完整、逐字】输出保存到一个文件中：
   write_file("/research/<地区>/sources.md", ...)。把工具返回的结果原样粘贴进去——
   包括每条结果的标题、URL 和完整内容摘要。不要做总结、删减或重新排版。
   这一个文件就是你的原始存档：所有冗长的材料都留在这里，
   这样它们绝不会把编辑者的上下文弄乱。
3. 然后，才从你找到的内容中写出一段精炼的总结片段。

只把完成后的片段作为你的回复返回：
- 一个 Markdown 小节：一个 "## <地区>" 标题，后跟约 120-180 词。
- 不要把原始搜索结果或链接列表粘贴进你的回复——那些存在于你的研究文件中。
  只返回润色后的片段。"""

genre_researcher = {
    "name": "genre_researcher",
    "description": "调研一个旅游地区，并返回一段关于这个地区的总结。每个地区作为一个单独的任务委派",
    "system_prompt": GENRE_SYSTEM_PROMPT,
    "model": model,
    "permissions": [
        FilesystemPermission(
            operations=["read", "write"], paths=["/research/**"], mode="allow"
        ),
        FilesystemPermission(operations=["read", "write"], paths=["/**"], mode="deny"),
    ],
    "tools": [search_news],
}

MAIN_SYSTEM_PROMPT = """
你是一个旅游攻略的编辑。
你需要调研以下几个地区的旅游攻略：
赛里木湖,三亚,青岛,华山,武当山。

你的职责：
1. 对每种地区，使用 task 工具把任务委派给 genre-researcher 子代理——
   并行地把它们派出去。告诉每个子代理要报道哪种流派、使用哪个被分配到的
   文件夹（/research/<地区>/），并让它返回一段总结。
2. 收集返回的总结。不要自己去做流派调研。
3. 把它们组装成一份 Markdown 文档
4. 对组装好的 Markdown 调用 markdown_to_html，然后把返回的 HTML 通过
   write_file 写入 /output/newsletter.html。

把你的上下文聚焦在协调与组装上。"""

agent = create_deep_agent(
    model=model,
    permissions=[
        FilesystemPermission(operations=["write"], paths=["/research/**"], mode="deny"),
    ],
    system_prompt=MAIN_SYSTEM_PROMPT,
    subagents=[genre_researcher],
    tools=[markdown_to_html],
    backend=FilesystemBackend(root_dir=DATA_DIR, virtual_mode=True),
)

from langchain.messages import HumanMessage

res = agent.invoke(HumanMessage("开始任务"))
print(res["messages"][-1].content)
